name = "narzo-store"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]
pages_build_output_dir = "dist"

[[d1_databases]]
binding = "DB"
database_name = "narzo-db"
database_id = "93680d63-befd-4a65-adbb-0a8e08181639"

[[kv_namespaces]]
binding = "SESSIONS"
id = "551e108604db4f82b35728d82cb81f6d"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "narzo-media"
