name = "narzo-store"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]
main = "dist/_worker.js"

[assets]
directory = "dist"
binding = "ASSETS"

[[d1_databases]]
binding = "DB"
database_name = "narzo-db"
database_id = "93680d63-befd-4a65-adbb-0a8e08181639"

[[kv_namespaces]]
binding = "SESSIONS"
id = "fda35e24a56542b7ba803fd66965a1d3"

[[r2_buckets]]
binding = "MEDIA"
bucket_name = "narzo-media"
